formatting_style = "Full"

[ticket_server]
addr = "127.0.0.1:8080"

[ticket_server.cors]
allow_credentials = false
allow_origins = "Mirror"
allow_headers = "Mirror"
allow_methods = "Mirror"
max_age = 2592000
expose_headers = "All"

[data_server]
addr = "127.0.0.1:8081"

[data_server.cors]
allow_credentials = false
allow_origins = "Mirror"
allow_headers = "Mirror"
allow_methods = "Mirror"
max_age = 2592000
expose_headers = "All"

[service_info]

[[locations]]
prefix = ""

[locations.backend]
kind = "File"
scheme = "HTTP"
authority = "127.0.0.1:8081"
local_path = "./"

