# An example config file for a TLS data server that uses a local storage backend.
# Run with `cargo run -p htsget-axum --all-features -- --config htsget-config/docs/examples/tls_data_server.toml`

ticket_server.addr = "0.0.0.0:8080"
data_server.addr = "0.0.0.0:8081"
data_server.cors.allow_origins = "All"
data_server.tls.cert = "cert.pem"
data_server.tls.key = "key.pem"

locations = "file://data"

## Or, set using regex locations
#[[locations]]
#regex = ".*"
#substitution_string = "$0"
#backend.kind = "File"
#backend.local_path = "data"
