# An example for a server which uses url storage with data located at "http://localhost:3000".
# Run with
# `cargo run -p htsget-axum --all-features -- --config htsget-config/docs/examples/url_storage.toml`
# in the project directory.

ticket_server.addr = "127.0.0.1:8082"
ticket_server.cors.allow_origins = "All"

ticket_server.tls.cert = "cert.pem"
ticket_server.tls.key = "key.pem"

data_server = "None"

locations = "https://127.0.0.1:8081"

## Or, set using regex locations
#[[locations]]
#regex = ".*"
#substitution_string = "$0"
#
#backend.kind = "Url"
#backend.url = "http://127.0.0.1:8081"
#backend.response_url = "https://127.0.0.1:8081"
#backend.forward_headers = true
#
## Set client authentication
#backend.http.key = "key.pem"
#backend.http.cert = "cert.pem"
#
## Set root certificates
#backend.http.root_store = "root.crt"
#
## Disable HTTP caching
#backend.http.use_cache = false
