[workspace]
resolver = "2"

members = [
    "htsget-config",
    "htsget-actix",
    "htsget-http",
    "htsget-lambda",
    "htsget-search",
    "htsget-test"
]

[workspace.package]
license = "MIT"
edition = "2021"