[package]
name = "htsget-http-lambda"
version = "0.1.0"
authors = ["Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"

[dependencies]

envy = "0.4.2"
tokio = "1.17.0"
lambda_http = { version = "0.5.1" }
lambda_runtime = { version = "0.5.1" }
htsget-config = { path = "../htsget-config" }
htsget-search = { path = "../htsget-search" }
htsget-http-core = { path = "../htsget-http-core" }
serde = { version = "1.0.136" }
serde_json = "1.0.79"
mime = "0.3.16"
regex = "1.5.5"

[dev-dependencies]
htsget-test-utils = { path = "../htsget-test-utils" }
async-trait = "0.1"
query_map = "0.4"